name: windows run_tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    name: run_tests windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: install choco
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: install choco packages
        shell: powershell
        run: choco install openjdk make llvm msys2
        
      - name: refresh env
        shell: powershell
        run: refreshenv

      - name: run tests
        shell: powershell
        run: msys2_shell.cmd -msys2 -here -use-full-path -c "make"
