name: run c tests on windows

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  run_tests_c:
    name: windows run c tests
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@5beef6d11f48bba68b9eb503e3adc60b23c0cc36 # v2
        with:
          update: true
          path-type: minimal
          msystem: UCRT64
# git is used in Makefile: JAVA_FILE_TOOLS_VERSION
          install: >-
            make
            git
            mingw-w64-ucrt-x86_64-clang
            diffutils

      - name: install choco packages
        shell: powershell
        run: choco install openjdk --version 21.0.0

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v2.6.0

      # NYI this does not work :-( but why?
      # - name: set PATH
      #   run: echo "/ucrt64/bin/:/c/Program Files/OpenJDK/jdk-21/bin:$PATH" >> $GITHUB_PATH

      - name: echo PATH
        run: echo "$PATH"

      - name: echo versions
        run: |
          export PATH="/ucrt64/bin/:/c/Program Files/OpenJDK/jdk-21/bin:$JAVA_HOME/bin/server:$PATH"
          clang --version
          javac --version

      - name: build libgc
        run: |
          export PATH="/ucrt64/bin/:/c/Program Files/OpenJDK/jdk-21/bin:$JAVA_HOME/bin/server:$PATH"
          ./bin/windows_install_boehm_gc.sh

      - name: run tests
        run:  |
          export PATH="/ucrt64/bin/:/c/Program Files/OpenJDK/jdk-21/bin:$JAVA_HOME/bin/server:$PATH"
          export FUZION_CLANG_INSTALLED_DIR="D:/a/_temp/msys64/ucrt64/bin"
          # change default codepage to utf-8 and run tests
          # if we don't change codepage emoji world in tests/javaBase will not work
          chcp.com 65001 && make run_tests_c
