name: windows run_tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    name: run_tests windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            git
            
      - name: install choco packages
        shell: powershell
        run: choco install openjdk
        
      - name: list c
        shell: powershell
        run: ls /c/
      
      - uses: actions/checkout@v2
      
      - name: run tests
        run: make run_tests
